import { useState } from 'react';
import {
  FileText, Download, ShieldCheck,
  Calendar, Filter, RefreshCw, FileCheck
} from 'lucide-react';
import { Card, Badge, SectionHeader } from '../components/ui';

interface ReportItem {
  id: string;
  code: string;
  title: string;
  category: 'COMPLIANCE' | 'SECURITY_INCIDENT' | 'MAINTENANCE_AUDIT' | 'PLC_INTEGRITY';
  standard: string;
  generated_at: string;
  generated_by: string;
  status: 'READY' | 'GENERATING' | 'ARCHIVED';
  summary: string;
  risk_level?: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  file_size: string;
}

const REPORTS: ReportItem[] = [
  {
    id: 'rep-001',
    code: 'IEC-62443-2026-Q3',
    title: 'IEC 62443 Industrial Network & Logic Security Audit',
    category: 'COMPLIANCE',
    standard: 'IEC 62443-3-3 / ISA-99',
    generated_at: '2026-09-23T18:00:00Z',
    generated_by: 'Automated SOC Auditor',
    status: 'READY',
    summary: 'Full audit of CNC & Welding production cells against Zone & Conduit security architecture. 1 critical interlock violation flagged.',
    risk_level: 'CRITICAL',
    file_size: '3.4 MB',
  },
  {
    id: 'rep-002',
    code: 'INC-2026-0923-01',
    title: 'Incident Post-Mortem: Unauthorized N7 Safety Interlock Removal',
    category: 'SECURITY_INCIDENT',
    standard: 'Zero-Trust Maintenance Enforcement',
    generated_at: '2026-09-23T04:30:00Z',
    generated_by: 'SecOps Incident Response Team',
    status: 'READY',
    summary: 'Investigation of automated welding cell WLD-04. Unapproved bytecode removal of N7 interlock blocked at maintenance verification gateway.',
    risk_level: 'CRITICAL',
    file_size: '1.8 MB',
  },
  {
    id: 'rep-003',
    code: 'MNT-VERIF-2026-W38',
    title: 'Weekly Maintenance Verification & Zero-Trust Closure Summary',
    category: 'MAINTENANCE_AUDIT',
    standard: 'MaintX Gateway Policy v2.4',
    generated_at: '2026-09-22T23:59:00Z',
    generated_by: 'Supervisor S. Patel',
    status: 'READY',
    summary: 'Review of 4 maintenance work orders. 1 verified and closed, 1 in-progress, 1 rejected due to unapproved IP alteration.',
    risk_level: 'HIGH',
    file_size: '2.1 MB',
  },
  {
    id: 'rep-004',
    code: 'PLC-SHA256-LEDGER-09',
    title: 'Cryptographic Ledger Verification Certificate',
    category: 'PLC_INTEGRITY',
    standard: 'NIST SP 800-82r3 Cryptographic Log Standard',
    generated_at: '2026-09-23T12:00:00Z',
    generated_by: 'MaintX Authoritative Hash Chain',
    status: 'READY',
    summary: 'Validation of all 5 block hashes in the append-only ledger. Genesis hash: 00000000... unbroken chain confirmed.',
    risk_level: 'LOW',
    file_size: '940 KB',
  },
  {
    id: 'rep-005',
    code: 'ISO-27001-OT-ANNUAL',
    title: 'ISO/IEC 27001 Annex A.12 Operational Security Alignment',
    category: 'COMPLIANCE',
    standard: 'ISO/IEC 27001:2022',
    generated_at: '2026-09-20T09:15:00Z',
    generated_by: 'Compliance Officer D. Vance',
    status: 'READY',
    summary: 'Access control, parameter change logging, and segregation of duties assessment for industrial edge controller assets.',
    risk_level: 'LOW',
    file_size: '5.2 MB',
  },
];

export function ReportsPage() {
  const [filter, setFilter] = useState<string>('ALL');
  const [generating, setGenerating] = useState<boolean>(false);
  const [activeReport, setActiveReport] = useState<ReportItem | null>(null);

  const filtered = REPORTS.filter(r => filter === 'ALL' || r.category === filter);

  const handleGenerate = () => {
    setGenerating(true);
    setTimeout(() => {
      setGenerating(false);
      alert('New Compliance Audit Report generated and signed with current SHA-256 state.');
    }, 1500);
  };

  const downloadReport = (r: ReportItem) => {
    const content = `===============================================================
MAINTX INDUSTRIAL ZERO-TRUST CYBERSECURITY REPORT
===============================================================
Report Code:    ${r.code}
Title:          ${r.title}
Category:       ${r.category}
Standard:       ${r.standard}
Generated:      ${r.generated_at}
Generated By:   ${r.generated_by}
Risk Level:     ${r.risk_level || 'N/A'}
Cryptographic State: SHA-256 Chain Intact
===============================================================

EXECUTIVE SUMMARY:
${r.summary}

AUTOMATED FINDINGS:
1. PLC Logic Verification: Active comparison of Canonicalized AST against trusted baseline.
2. Parameter Enforcement: Motor speed setpoint, thermal thresholds, and IP network bounds verified.
3. Cryptographic Tamper-Evidence: Previous block hash validated against current ledger state.

CERTIFICATION:
Digitally signed by MaintX Authoritative Backend Core.
Unauthorized maintenance closure blocked where unresolved critical changes exist.
===============================================================`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${r.code}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <SectionHeader
        icon={<FileText className="w-5 h-5" />}
        title="Industrial Compliance & Security Reports"
        subtitle="Cryptographically grounded audit reports for IEC 62443, NIST SP 800-82, and ISO 27001"
        actions={
          <button
            onClick={handleGenerate}
            disabled={generating}
            className="flex items-center gap-2 px-3 py-2 rounded-lg bg-cyan-950/60 border border-cyan-700/50 text-cyan-300 text-xs font-mono hover:bg-cyan-900/60 transition disabled:opacity-50"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${generating ? 'animate-spin' : ''}`} />
            {generating ? 'Generating Signatures…' : 'Generate Compliance Package'}
          </button>
        }
      />

      {/* Highlights Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
        {[
          { label: 'Total Reports', val: REPORTS.length, sub: 'Archived & Verified', color: 'text-cyan-400' },
          { label: 'Compliance Standards', val: 'IEC 62443 / ISO 27001', sub: 'Active frameworks', color: 'text-indigo-400' },
          { label: 'Incident Reports', val: '1 Open / 0 Unmitigated', sub: 'Safety Gate Enforced', color: 'text-rose-400' },
          { label: 'Audit Seal', val: 'SHA-256 Validated', sub: 'Hardware Root of Trust', color: 'text-emerald-400' },
        ].map((item, i) => (
          <Card key={i} className="p-4">
            <span className="text-[10px] font-mono text-slate-500 uppercase">{item.label}</span>
            <p className={`text-xl font-bold font-mono mt-1 ${item.color}`}>{item.val}</p>
            <p className="text-[10px] text-slate-500 mt-1">{item.sub}</p>
          </Card>
        ))}
      </div>

      {/* Filter Tabs */}
      <div className="flex items-center gap-2 flex-wrap border-b border-slate-800/80 pb-3">
        <Filter className="w-4 h-4 text-slate-500" />
        {['ALL', 'COMPLIANCE', 'SECURITY_INCIDENT', 'MAINTENANCE_AUDIT', 'PLC_INTEGRITY'].map(cat => (
          <button
            key={cat}
            onClick={() => setFilter(cat)}
            className={`px-3 py-1.5 rounded-lg text-xs font-mono transition border ${
              filter === cat
                ? 'bg-cyan-950/70 border-cyan-500/50 text-cyan-300'
                : 'border-slate-800 text-slate-400 hover:text-slate-200 hover:bg-slate-800/40'
            }`}
          >
            {cat.replace(/_/g, ' ')}
          </button>
        ))}
      </div>

      {/* Reports Listing */}
      <div className="space-y-4">
        {filtered.map(report => (
          <Card key={report.id} className="p-5 hover:border-slate-700 transition">
            <div className="flex flex-col md:flex-row md:items-start justify-between gap-4">
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2.5 flex-wrap mb-1.5">
                  <span className="px-2 py-0.5 rounded bg-slate-900 border border-slate-700 font-mono text-[10px] text-cyan-400 font-semibold">
                    {report.code}
                  </span>
                  <span className="text-[11px] font-mono text-slate-400">
                    {report.standard}
                  </span>
                  {report.risk_level && (
                    <Badge riskLevel={report.risk_level}>{report.risk_level}</Badge>
                  )}
                </div>

                <h3 className="text-base font-bold text-white tracking-tight hover:text-cyan-400 transition">
                  {report.title}
                </h3>

                <p className="text-xs text-slate-300 mt-2 leading-relaxed">
                  {report.summary}
                </p>

                <div className="flex items-center gap-4 text-[10px] font-mono text-slate-500 mt-3 pt-3 border-t border-slate-800/60">
                  <span className="flex items-center gap-1">
                    <Calendar className="w-3 h-3 text-slate-500" />
                    {new Date(report.generated_at).toLocaleString()}
                  </span>
                  <span className="flex items-center gap-1">
                    <ShieldCheck className="w-3 h-3 text-cyan-500" />
                    {report.generated_by}
                  </span>
                  <span>Size: {report.file_size}</span>
                </div>
              </div>

              {/* Actions */}
              <div className="flex md:flex-col items-center gap-2 flex-shrink-0">
                <button
                  onClick={() => downloadReport(report)}
                  className="w-full flex items-center justify-center gap-2 px-3 py-2 rounded-lg bg-cyan-950/40 border border-cyan-800/40 text-cyan-300 text-xs font-mono hover:bg-cyan-900/40 transition"
                  title="Download encrypted audit package"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Download .TXT</span>
                </button>
                <button
                  onClick={() => setActiveReport(report)}
                  className="w-full flex items-center justify-center gap-1.5 px-3 py-2 rounded-lg bg-slate-900 border border-slate-800 text-slate-300 text-xs font-mono hover:border-slate-600 transition"
                >
                  <FileCheck className="w-3.5 h-3.5 text-emerald-400" />
                  <span>Inspect Digest</span>
                </button>
              </div>
            </div>
          </Card>
        ))}
      </div>

      {/* Inspect Modal */}
      {activeReport && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
          <Card className="w-full max-w-2xl p-6 bg-[#0a0f1d] border-cyan-800/60 shadow-2xl relative">
            <div className="flex items-start justify-between border-b border-slate-800 pb-4 mb-4">
              <div>
                <span className="text-[10px] font-mono text-cyan-400 uppercase tracking-widest">
                  CRYPTOGRAPHIC ATTESTATION DIGEST
                </span>
                <h3 className="text-lg font-bold text-white mt-1">{activeReport.title}</h3>
                <p className="text-xs text-slate-400 font-mono mt-0.5">{activeReport.code} · {activeReport.standard}</p>
              </div>
              <button
                onClick={() => setActiveReport(null)}
                className="text-slate-400 hover:text-white font-mono text-lg"
              >
                ✕
              </button>
            </div>

            <div className="space-y-3 text-xs font-mono">
              <div className="p-3 rounded bg-slate-950/70 border border-slate-800 space-y-1">
                <span className="text-slate-500 uppercase text-[10px]">Ledger Head Hash</span>
                <p className="text-emerald-400 break-all select-all">
                  e5f6a7b8c9d0e5f6a7b8c9d0e5f6a7b8c9d0e5f6a7b8c9d0e5f6a7b8c9d0e5f6
                </p>
              </div>
              <div className="p-3 rounded bg-slate-950/70 border border-slate-800 space-y-1">
                <span className="text-slate-500 uppercase text-[10px]">PLC Logic Verified State</span>
                <p className="text-slate-300">Baseline Canonical AST SHA-256 match validated.</p>
              </div>
              <div className="p-3 rounded bg-slate-950/70 border border-slate-800 space-y-1">
                <span className="text-slate-500 uppercase text-[10px]">Compliance Attestation</span>
                <p className="text-slate-300">
                  Meets IEC 62443 Technical Security Requirements (SL-T Level 3). Unauthorized state changes require physical supervisor key override.
                </p>
              </div>
            </div>

            <div className="flex justify-end gap-3 mt-6 pt-4 border-t border-slate-800">
              <button
                onClick={() => setActiveReport(null)}
                className="px-4 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-mono transition"
              >
                Close
              </button>
              <button
                onClick={() => {
                  downloadReport(activeReport);
                  setActiveReport(null);
                }}
                className="px-4 py-2 rounded-lg bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-mono transition flex items-center gap-2"
              >
                <Download className="w-3.5 h-3.5" />
                Export Verified Report
              </button>
            </div>
          </Card>
        </div>
      )}
    </div>
  );
}
